version: "3.0"

services:
  blessing:
    container_name: blessing
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "58030:8000"
    volumes:
      - ${BACKUP}:/root/data
    env_file: .env

