# Generated by Django 4.1.2 on 2022-10-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_search_modified_search_name_search_query'),
        ('comments', '0004_comment_link_tweet_last_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.search')),
            ],
        ),
    ]
