# Generated by Django 4.1.2 on 2022-10-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=48)),
                ('query', models.CharField(default='', max_length=255)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
